#! /usr/bin/env python2
# -*- coding: utf-8 -*-

import logging
import os
import platform

from lab.calls.call import Call
from lab import tools

tools.configure_logging()

logging.info('node: {}'.format(platform.node()))

run_log = open('run.log', 'w')
run_err = open('run.err', 'w')
redirects = {'stdout': run_log, 'stderr': run_err}

# Make sure we're in the run directory.
os.chdir(os.path.dirname(os.path.abspath(__file__)))

Call(['bfws', '--domain', 'domain.pddl', '--problem', 'p01-6-4-2.pddl', '--output', '', '--max_novelty', '2', '--k-BFWS', 'true'], hard_stderr_limit=10240, hard_stdout_limit=10240, memory_limit=4096, name='run-planner', soft_stderr_limit=64, soft_stdout_limit=1024, time_limit=300, **redirects).wait()

Call(['../../bfws-parser.py'], hard_stderr_limit=10240, hard_stdout_limit=10240, memory_limit=None, name='bfws_parser', soft_stderr_limit=64, soft_stdout_limit=1024, time_limit=None, **redirects).wait()


for f in [run_log, run_err]:
    f.close()
    if os.path.getsize(f.name) == 0:
        os.remove(f.name)
